---
name: Bump Version

"on":
  push:
    branches: [main]
  workflow_dispatch: null # For manual runs

jobs:
  bump-version:
    # Ignore the commits from this action
    if: "!startsWith(github.event.head_commit.message, 'bump:')"
    runs-on: ubuntu-22.04
    name: Bump version and make release with commitizen
    # Fix 403 error (https://github.com/softprops/action-gh-release/issues/400)
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Bump version and generate changelog
        uses: commitizen-tools/commitizen-action@master
        with:
          branch: main
          changelog_increment_filename: body.md
          github_token: ${{ secrets.GITHUB_TOKEN }}

      - name: Generate GitHub Release Notes
        uses: softprops/action-gh-release@v2
        with:
          body_path: body.md
          tag_name: ${{ env.REVISION }}
